image: python:3.6

before_script:
- pip3 install -r requirements.txt

pages:
  script:
  - pip3 install -r requirements.txt
  - pip3 install -r apidocs/requirements.txt
  - sh ./apidocs/build_docs.sh
  artifacts:
    paths:
    - public
  only:
  - py3_docs
