image: debian

before_script:
  - apt update -qq
  - apt install -y -qq python3-pip python3-dev python3-pyqt5 python3-pyqt5.qtsvg python3-matplotlib python3-numpy python3-pyqt5.qtwebengine

stages:
  - test
  - pages

test:
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - export PYTHONPATH=$PYTHONPATH:.
  - python3 setup.py test

pages:
  script:
  - pip3 install -r apidocs/requirements.txt
  - mkdir public
  - sphinx-build -a -b html ./apidocs ./public/
  artifacts:
    paths:
    - public
  only:
  - master

