image: python:3.6

before_script:
- pip3 install -r requirements.txt

pages:
  script:
  - pip3 install -r requirements.txt
  - pip3 install -r apidocs/requirements.txt
  - sphinx-build -a -b apidocs public/
  artifacts:
    paths:
    - public
  only:
  - py3_docs
